version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: jacobkl/backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media 
  frontend:
    env_file: .env
    image: jacobkl/frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: jacobkl/gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media    