# Generated by Django 4.2.4 on 2023-09-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_reсipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reсipe',
            options={'ordering': ['-id']},
        ),
    ]
